### ISSUE TITLE
Collision system example?

### ISSUE THREAD

**Issue by JaredSartin** [tenjou/meta2d#42]
Sorry about all the commits. Meta2D looks to be the tool I need for the game I am working on, so I am really pushing to get a prototype done with it.

But I digress. How would i quickly get the AABB collisions working? Is there sample code for 2 entities colliding that I can look at?

**Comment by tenjou** [comment]
No problems, it`s maybe better if you write me in discord so that i can help you in more timely manner (Tenjou#2747).

Demo: http://meta2d.com/tests/physics/
```javascript
meta.onLoad = function() 
{
	meta.resources.loadTexture([ "circle" ], "assets/");
}

meta.onReady = function()
{
	for(let n = 0; n < 30; n++)
	{
		const entity = new Entity.Geometry("circle");
		entity.pivot(0.5);
		entity.position(meta.world.randX, meta.world.randY);
		const body = entity.addComponent(Physics.Body);
		body.volume = new meta.math.Circle(entity.volume.x, entity.volume.y, entity.volume.halfWidth - 1); // This is optional line, if left unchanged it will take entity AABB.
		body.velocity.x = (meta.random.number(-60, 60) + 80);
		body.velocity.y = (meta.random.number(-60, 60) + 80);
		body.worldBounds = true;
		body.bouncing = true; // Currently not working with AABB, have to take look into it.
		body.onCollision = function(manifold) {

		}
		meta.view.attach(entity);
	}	
}
```

Meta2D is pretty rough at this moment and i`m currently rebuilding engine to use ECMA6, editor(https://pbs.twimg.com/media/Cqh_G_6W8AAnCii.jpg:large), so it will probably take a bit time to polish things.

**Comment by JaredSartin** [comment]
Thanks, I think this will be all I need. Just need to see when one entity hits another for removal!
